### ISSUE TITLE
Issues using with Karma/Jasmine

### ISSUE THREAD

**Issue by mgan59** [awei01/fluxxor-test-utils#6]
Was trying to test some react components that use fluxxor stores.  I followed your code examples and ran into several issues.

First 

> ### Unit testing a react component that uses Flux
> ```js
describe('Testing my component', function() {
    var React, TestUtils, FluxxorTestUtils, fakeFlux, MyComponent;
    beforeEach(function() {
        React = require('react/addons');
        TestUtils = React.addons.TestUtils;
        FluxxorTestUtils = require('fluxxor-test-utils');
        fakeFlux = FluxxorTestUtils({ MyStore: new require('../my-store') }, require('../my-actions'));
        fakeFlux.genMocksForStoresAndActions();
        // now all store and action methods are mocked for testing
        MyComponent = require('../my-component');
    });
    it('when mounted, it should call .getFooValue() on my store and set state.foo', function() {
        var store = fakeFlux.stores.MyStore; // easier reference to our store
        var component;
        store.getFooValue.mockReturnValue('value from store');
        component = TestUtils.renderIntoDocument(MyComponent({ flux: fakeFlux });
        expect(store.getFooValue).toBeCalled();
        expect(component.state.foo).toBe('value from store');
    });
    it('when mounted and clicked, should call actions.doFooAction()', function() {
        var component = TestUtils.renderIntoDocument(MyComponent({ flux: fakeFlux });
        TestUtils.Simulate.click(component.getDOMNode());
        expect(fakeFlux.actions.doFooAction).toBeCalled();
    });
});
```

Should the line 

> `fakeFlux = FluxxorTestUtils({ MyStore: new require('../my-store') }, require('../my-actions'));`

actual use the exposed factory method?

> `fakeFlux = FluxxorTestUtils.fakeFlux({ MyStore: new require('../my-store') }, require('../my-actions'));`

This seemed to move me forward, but there were additional exceptions being thrown and the test runner was eating it so made it hard to gain visibility into the issue.

I did capture this error about needing `Jest` which I don't use because I'm inside the karma/test runner.

```sh
✗ Ensure component is rendered TableControl
	ReferenceError: jest is not defined
	    at getJest (/var/folders/73/k63gp8n90mj8_xzm1zn13sv00000gn/T/550e2b4d69df7f35f9141752f8ffed81.browserify:994:27 <- node_modules/fluxxor-test-utils/lib/jest-utils.js:24:0)
	    at /var/folders/73/k63gp8n90mj8_xzm1zn13sv00000gn/T/550e2b4d69df7f35f9141752f8ffed81.browserify:983:19 <- node_modules/fluxxor-test-utils/lib/jest-utils.js:13:0
	    at Function.forIn (/var/folders/73/k63gp8n90mj8_xzm1zn13sv00000gn/T/550e2b4d69df7f35f9141752f8ffed81.browserify:7627:15 <- node_modules/lodash/dist/lodash.js:2023:0)
	    at Object.mockObjectWithJest (/var/folders/73/k63gp8n90mj8_xzm1zn13sv00000gn/T/550e2b4d69df7f35f9141752f8ffed81.browserify:975:4 <- node_modules/fluxxor-test-utils/lib/jest-utils.js:5:0)
	    at null.<anonymous> (/var/folders/73/k63gp8n90mj8_xzm1zn13sv00000gn/T/550e2b4d69df7f35f9141752f8ffed81.browserify:905:13 <- node_modules/fluxxor-test-utils/lib/fake-flux.js:47:0)
	    at /var/folders/73/k63gp8n90mj8_xzm1zn13sv00000gn/T/550e2b4d69df7f35f9141752f8ffed81.browserify:6505:23 <- node_modules/lodash/dist/lodash.js:901:0
	    at Function.forEach (/var/folders/73/k63gp8n90mj8_xzm1zn13sv00000gn/T/550e2b4d69df7f35f9141752f8ffed81.browserify:8901:15 <- node_modules/lodash/dist/lodash.js:3297:0)
	    at FakeFlux.genMocksForStores (/var/folders/73/k63gp8n90mj8_xzm1zn13sv00000gn/T/550e2b4d69df7f35f9141752f8ffed81.browserify:900:4 <- node_modules/fluxxor-test-utils/lib/fake-flux.js:42:0)
	    at FakeFlux.genMocksForStoresAndActions (/var/folders/73/k63gp8n90mj8_xzm1zn13sv00000gn/T/550e2b4d69df7f35f9141752f8ffed81.browserify:922:25 <- node_modules/fluxxor-test-utils/lib/fake-flux.js:64:0)
```

Looking at the [code](https://github.com/awei01/fluxxor-test-utils/blob/master/lib/fake-flux.js#L37) it appears the JestUtils are required no matter what which in the end require the [global existence](https://github.com/awei01/fluxxor-test-utils/blob/master/lib/jest-utils.js#L24) of `jest`.

Could you clarify if this library is compatible with karma/jasmine?

**Comment by awei01** [comment]
Currently if you implement `.genMocksForStores` or `.genMocksForActions`  (or any of its derivatives), you'll need to install `jest`. I know it's not the best formatted `readme`, but, it does mention that `jest` is required for the above methods. 

I believe there is a workaround if you're not using `jest` for testing, though. Referring to the jasmine docs (http://jasmine.github.io/2.0/introduction.html), you can do something like this (untested code follows):

```

describe('some test', function() {
    var React, TestUtils, FluxxorTestUtils, fakeFlux, MyComponent, myStore, myActions;
    beforeEach(function() {
        React = require('react/addons');
        TestUtils = React.addons.TestUtils;
        FluxxorTestUtils = require('fluxxor-test-utils');
        myStore = new require('../my-store');
        myActions = new require('../my-actions');
        fakeFlux = FluxxorTestUtils({ MyStore: myStore }, myActions);
        MyComponent = require('../my-component');
    });
    it('when mounted, it should call .getFooValue() on my store and set state.foo', function() {
        var store = fakeFlux.stores.MyStore; // easier reference to our store
        var component;
        spyOn(store, 'getFooValue').and.returnValue('value from store');
        component = TestUtils.renderIntoDocument(MyComponent({ flux: fakeFlux });
        expect(store.getFooValue).toHaveBeenCalled();
        expect(component.state.foo).toBe('value from store');
    });
});

```

Hope that helps...
